// Spanish for the owner dashboard. Keyed by the exact English text used in the UI,
// so components just call tx("English text") and fall back to English if missing.
export const adminEs: Record<string, string> = {
  // shell + tabs
  "Dashboard": "Panel",
  "View site ↗": "Ver sitio ↗",
  "Sign out": "Cerrar sesión",
  "Dashboard sections": "Secciones del panel",
  "Bookings": "Reservas",
  "Services": "Servicios",
  "Add-ons": "Complementos",
  "Team": "Equipo",
  "Portfolio": "Portafolio",
  "Reviews": "Reseñas",
  "FAQ": "Preguntas frecuentes",
  "Shop & site": "Barbería y sitio",
  "Loading…": "Cargando…",

  // login + gates
  "Owner login": "Acceso del propietario",
  "Welcome back": "Bienvenido(a) de nuevo",
  "Email": "Correo electrónico",
  "Password": "Contraseña",
  "Sign in": "Iniciar sesión",
  "Signing in…": "Iniciando sesión…",
  "That username or password is incorrect.": "Ese usuario o contraseña es incorrecto.",
  "Username": "Usuario",
  "Supabase isn’t configured. Add NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY to .env.local.": "Supabase no está configurado. Agrega NEXT_PUBLIC_SUPABASE_URL y NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY en .env.local.",
  "One-time database setup": "Configuración única de la base de datos",
  "Open your Supabase project → SQL Editor → New query, paste the contents of supabase/schema.sql from this project, and press Run. Then reload this page.": "Abre tu proyecto de Supabase → SQL Editor → New query, pega el contenido de supabase/schema.sql de este proyecto y presiona Run. Luego recarga esta página.",
  "Not authorized": "No autorizado",
  "Claim this website": "Reclamar este sitio",
  "This account isn’t the owner of this site. Sign out and use the owner login.": "Esta cuenta no es la propietaria de este sitio. Cierra sesión y usa el acceso del propietario.",
  "No owner has been set up yet. If you’re the salon owner, claim the dashboard now. This can only be done once.": "Aún no hay un propietario configurado. Si eres el dueño o la dueña del salón, reclama el panel ahora. Solo se puede hacer una vez.",
  "I’m the owner. Claim it": "Soy el propietario(a). Reclamar",

  // banners + notes
  "Your website is showing sample content.": "Tu sitio web está mostrando contenido de muestra.",
  "Load the starter services, portfolio, reviews and FAQ into your database so you can edit them here.": "Carga los servicios, portafolio, reseñas y preguntas de ejemplo en tu base de datos para poder editarlos aquí.",
  "Load starter content": "Cargar contenido de ejemplo",
  "Load the starter services, portfolio, reviews and FAQ into your database? You can edit or delete everything afterwards.": "¿Cargar los servicios, portafolio, reseñas y preguntas de ejemplo en tu base de datos? Después podrás editar o borrar todo.",
  "Starter content loaded. Edit anything from the tabs.": "Contenido de ejemplo cargado. Edita lo que quieras desde las pestañas.",
  "Turn on Spanish for your content": "Activa el español para tu contenido",
  "One-time step: open Supabase → SQL Editor → New query, paste this, press Run, then reload this page.": "Paso único: abre Supabase → SQL Editor → New query, pega esto, presiona Run y recarga esta página.",
  "Copy SQL": "Copiar SQL",
  "Copied ✓": "Copiado ✓",
  "Add Spanish to your starter content": "Agrega español a tu contenido de ejemplo",
  "Visitors can switch the site to Spanish. Add ready-made Spanish for the starter services, portfolio, reviews and FAQ now; you can edit any of it afterwards.": "Los visitantes pueden cambiar el sitio a español. Agrega ahora el español ya preparado para los servicios, portafolio, reseñas y preguntas de ejemplo; después puedes editar lo que quieras.",
  "Add Spanish translations": "Agregar traducciones al español",
  "Spanish added to the starter content. Review it in each section (look for the “Español” boxes).": "Español agregado al contenido de ejemplo. Revísalo en cada sección (busca las cajas “Español”).",

  // section titles + blurbs
  "What clients can book. Price is the “from” price; duration controls how much calendar time it takes.": "Lo que los clientes pueden reservar. El precio es el precio “desde”; la duración define cuánto tiempo ocupa en el calendario.",
  "Optional extras clients can tack onto a service.": "Extras opcionales que los clientes pueden añadir a un servicio.",
  "People shown in “Meet the crew” under the homepage banner. If this is empty, that section is hidden.": "Personas que aparecen en “Conoce al equipo” debajo del banner de inicio. Si está vacío, esa sección no se muestra.",
  "Upload your best work. Add a “before” photo to turn on the before/after slider.": "Sube tu mejor trabajo. Agrega una foto de “antes” para activar el deslizador antes/después.",
  "Client words on the Stories tab. Only add real reviews you have permission to share.": "Palabras de clientes en la pestaña Reseñas. Agrega solo reseñas reales que tengas permiso de compartir.",
  "Questions shown on the Studio tab.": "Preguntas que aparecen en la pestaña Barbería.",

  // field labels + hints
  "Service name": "Nombre del servicio",
  "Category": "Categoría",
  "Description": "Descripción",
  "Starting price ($)": "Precio desde ($)",
  "Duration (minutes)": "Duración (minutos)",
  "Deposit ($)": "Depósito ($)",
  "0 = no deposit": "0 = sin depósito",
  "Name": "Nombre",
  "Short description": "Descripción corta",
  "Price ($)": "Precio ($)",
  "Adds (minutes)": "Suma (minutos)",
  "After photo (main image)": "Foto del después (imagen principal)",
  "Before photo (optional, enables the slider)": "Foto del antes (opcional, activa el deslizador)",
  "Title": "Título",
  "Linked service id": "ID del servicio vinculado",
  "The “Book this look” button preselects this service. Copy an id from the Services tab URL list, p. ej. skin-fade.": "El botón “Reservar este look” preselecciona este servicio. Escribe el id del servicio, p. ej. blonde-balayage.",
  "Story": "Historia",
  "Time in chair (label)": "Tiempo en la silla (texto)",
  "e.g. 3.5 hrs": "p. ej. 3.5 h",
  "Placeholder art style": "Estilo del arte provisional",
  "Only used when no photo is uploaded.": "Solo se usa si no se sube una foto.",
  "Colors (placeholder art): hair, skin, accent": "Colores (arte provisional): cabello, piel, acento",
  "Photo": "Foto",
  "Role": "Cargo",
  "e.g. Fade specialist": "p. ej. Especialista en fades",
  "Short bio": "Biografía corta",
  "Instagram handle": "Usuario de Instagram",
  "without the @": "sin el @",
  "Client name": "Nombre del cliente",
  "Service they had": "Servicio que recibió",
  "Review": "Reseña",
  "Stars (1–5)": "Estrellas (1–5)",
  "Question": "Pregunta",
  "Answer": "Respuesta",
  // select options
  "Fades": "Fades",
  "Cuts": "Cortes",
  "Beard": "Barba",
  "Combos": "Combos",
  "Tapers": "Tapers",
  "Beards": "Barbas",
  "Styles": "Estilos",
  "skin": "fade a piel",
  "low": "taper bajo",
  "mid": "fade medio",
  "crop": "corto",
  "top": "largo arriba",
  "beard": "barba",


  // profile / page text / shop tabs
  "Barber profile": "Perfil del barbero",
  "Page text": "Textos de la página",
  "Shop & contact": "Barbería y contacto",
  "The “Meet James” section on the homepage: his photo, name, headline, bio and the labels around it.": "La sección “Conoce a James” del inicio: su foto, nombre, título, biografía y las etiquetas alrededor.",
  "The hero headline, the ticker under it, the aftercare tips and the gift cards on the Shop tab.": "El título principal, la cinta de palabras debajo, los consejos de cuidado y las tarjetas de regalo de la pestaña Barbería.",
  "Shop name, address, phone, hours and booking rules.": "Nombre de la barbería, dirección, teléfono, horario y reglas de reservas.",
  "Barber name": "Nombre del barbero",
  "Shown in the “Meet …” heading (first name) and the hero.": "Aparece en el título “Conoce a …” (primer nombre) y en la portada.",
  "Labels around it": "Etiquetas alrededor",
  "Small label above the heading": "Etiqueta pequeña sobre el título",
  "Blank = “Your barber”.": "Vacío = “Tu barbero”.",
  "Word before the name": "Palabra antes del nombre",
  "Blank = “Meet”.": "Vacío = “Conoce a”.",
  "Button text": "Texto del botón",
  "Blank = “Book a cut”.": "Vacío = “Reservar un corte”.",
  "The three numbers": "Los tres números",
  "Hero headline": "Título principal",
  "Blank = built-in text.": "Vacío = texto predeterminado.",
  "Word 1": "Palabra 1",
  "Word 2 (colored)": "Palabra 2 (de color)",
  "Word 3": "Palabra 3",
  "Ticker under the hero": "Cinta de palabras bajo la portada",
  "Ticker words": "Palabras de la cinta",
  "Separate with commas. Blank = built-in list.": "Sepáralas con comas. Vacío = lista predeterminada.",
  "Aftercare tips": "Consejos de cuidado",
  "Shown at the bottom of the Shop tab.": "Se muestran al final de la pestaña Barbería.",
  "Using the built-in four tips.": "Usando los cuatro consejos predeterminados.",
  "Customize the tips": "Personalizar los consejos",
  "+ Add a tip": "+ Agregar un consejo",
  "Back to the built-in tips": "Volver a los consejos predeterminados",
  "Tip": "Consejo",
  "Gift cards": "Tarjetas de regalo",
  "Show the gift card box": "Mostrar el recuadro de tarjetas de regalo",
  "Gift card amounts ($)": "Montos de tarjetas de regalo ($)",
  "Separate with commas.": "Sepáralos con comas.",
  "Service for this cut": "Servicio para este corte",
  "The “Book this cut” button on the portfolio preselects this service.": "El botón “Reservar este corte” del portafolio preselecciona este servicio.",
  "— none —": "— ninguno —",
  "About headline": "Título de “Acerca de”",
  "Shown on the homepage → Menu tab and in booking. Price is the “from” price; duration controls how much calendar time it takes.": "Aparece en el inicio → pestaña Menú y al reservar. El precio es el precio “desde”; la duración define cuánto tiempo ocupa en el calendario.",
  "Shown on the Menu tab and offered during booking. Optional extras clients can add to a service.": "Aparece en la pestaña Menú y se ofrece al reservar. Extras opcionales que los clientes pueden añadir a un servicio.",
  "Shown on the Portfolio page. Upload your best work (photos), and add a “before” photo to turn on the before/after slider.": "Aparece en la página Portafolio. Sube tu mejor trabajo (fotos) y agrega una foto de “antes” para activar el deslizador antes/después.",
  "Shown on the homepage → Stories tab. Only add real reviews you have permission to share.": "Aparece en el inicio → pestaña Reseñas. Agrega solo reseñas reales que tengas permiso de compartir.",
  "Shown on the homepage → Shop tab.": "Aparece en el inicio → pestaña Barbería.",
  "Other barbers shown in “Meet the crew” under the homepage banner (photo, name, role, bio). James has his own section under Barber profile; if this list is empty the crew section is hidden.": "Otros barberos que aparecen en “Conoce al equipo” debajo del banner (foto, nombre, cargo, biografía). James tiene su propia sección en Perfil del barbero; si esta lista está vacía, la sección del equipo se oculta.",

  // list editor
  "+ Add new": "+ Agregar",
  "Nothing here yet. Click “Add new”.": "Aún no hay nada. Haz clic en “Agregar”.",
  "Move up": "Subir",
  "Move down": "Bajar",
  "Untitled": "Sin título",
  "Hidden": "Oculto",
  "Edit": "Editar",
  "Close": "Cerrar",
  "Show on website": "Mostrar en el sitio web",
  "Save changes": "Guardar cambios",
  "Saving…": "Guardando…",
  "Delete": "Eliminar",
  "Saved. Your website is updated.": "Guardado. Tu sitio web ya está actualizado.",
  "Deleted.": "Eliminado.",
  "Delete “{name}”? This can't be undone.": "¿Eliminar “{name}”? No se puede deshacer.",
  "This section needs a one-time database update. Open Supabase → SQL Editor → New query, paste the SQL below, press Run, then reload this page.": "Esta sección necesita una actualización única de la base de datos. Abre Supabase → SQL Editor → New query, pega el SQL de abajo, presiona Run y recarga esta página.",
  "Spanish support needs a one-time database update. Open Supabase → SQL Editor → New query, paste the SQL below, press Run, then reload this page and save again.": "El soporte en español necesita una actualización única de la base de datos. Abre Supabase → SQL Editor → New query, pega el SQL de abajo, presiona Run, recarga esta página y guarda de nuevo.",

  // images
  "No photo": "Sin foto",
  "Replace": "Reemplazar",
  "Upload": "Subir",
  "Remove": "Quitar",
  "Uploading…": "Subiendo…",
  "Please choose an image file.": "Elige un archivo de imagen.",
  "Image is over 8 MB. Please choose a smaller one.": "La imagen supera 8 MB. Elige una más pequeña.",

  // bookings
  "Upcoming": "Próximas",
  "Pending": "Pendientes",
  "All": "Todas",
  "Cancelled": "Canceladas",
  "New requests arrive as “pending”. Confirm them, or cancel to free the time slot again.": "Las solicitudes nuevas llegan como “pendientes”. Confírmalas, o cancélalas para liberar el horario.",
  "Refresh": "Actualizar",
  "No bookings in this view.": "No hay reservas en esta vista.",
  "Client:": "Cliente:",
  "(first visit)": "(primera visita)",
  "Phone:": "Teléfono:",
  "Email:": "Correo:",
  "Ref:": "Ref.:",
  "Confirm": "Confirmar",
  "Mark completed": "Marcar como completada",
  "Cancel": "Cancelar",
  "Restore": "Restaurar",
  "pending": "pendiente",
  "confirmed": "confirmada",
  "completed": "completada",
  "cancelled": "cancelada",
  "est.": "est.",
  "deposit": "depósito",
  "Permanently delete {name}'s booking?": "¿Eliminar definitivamente la reserva de {name}?",

  // studio settings
  "Shop & website": "Barbería y sitio web",
  "Your name, contact details, hours and the text on your site.": "Tu nombre, datos de contacto, horario y los textos de tu sitio.",
  "Shop": "Barbería",
  "Shop name": "Nombre de la barbería",
  "Big wordmark in the header": "Nombre grande en el encabezado",
  "Subtitle": "Subtítulo",
  "Small text beside the name": "Texto pequeño junto al nombre",
  "City": "Ciudad",
  "Street address": "Dirección",
  "Phone": "Teléfono",
  "Directions note": "Nota de indicaciones",
  "e.g. Free parking out front": "p. ej. Estacionamiento gratis al frente",
  "Homepage & about": "Inicio y acerca de",
  "Hero paragraph": "Párrafo principal",
  "About text": "Texto de “Acerca de”",
  "Portrait photo": "Foto de retrato",
  "Years of experience": "Años de experiencia",
  "Clients served": "Clientes atendidos",
  "shown as text, e.g. 4,200+": "se muestra como texto, p. ej. 4,200+",
  "Average rating": "Calificación promedio",
  "Look & feel": "Apariencia",
  "Default color shade": "Tono de color predeterminado",
  "Visitors can still change it themselves.": "Los visitantes pueden cambiarlo por su cuenta.",
  "Default mode": "Modo predeterminado",
  "Bone (light)": "Hueso (claro)",
  "Black (dark)": "Negro (oscuro)",
  "Opening hours": "Horario de atención",
  "Clients can only book inside these hours.": "Los clientes solo pueden reservar dentro de este horario.",
  "Closed": "Cerrado",
  "to": "a",
  "Time between start times (minutes)": "Tiempo entre horas de inicio (minutos)",
  "Minimum notice (hours)": "Aviso mínimo (horas)",
  "Stops same-hour bookings": "Evita reservas de último momento",
  "opens": "abre",
  "closes": "cierra",
};
